### ISSUE TITLE
trust-statistics.py fails with KeyError 'IGHA'

### ISSUE THREAD

**Issue by immuno-git** [liulab-dfci/TRUST4#171]
I processed one of my paired reads samples with TRUST4, and then wanted to quantify statistics on those samples using trust-statistics.py. However, when I ran it, the script failed with error 

> Traceback (most recent call last):
>   File "/Users/[name]/TRUST4/TRUST4/scripts/trust-stats.py", line 102, in <module>
>     chainType = GetChainType(cols[4], cols[6], cols[7])
>   File "/Users/[name]/TRUST4/TRUST4/scripts/trust-stats.py", line 23, in GetChainType
>     return (0, isotypeRanks[c])
> KeyError: 'IGHA'

Do you know what might be the cause of this? Thank you for your time and help.

**Comment by mourisl** [comment]
This script was written for human data. For customized isotypes, you can change the isotypeRank and isotypeOrder array at the top of the script. I do have the plan to make it more flexible in future versions.

**Comment by immuno-git** [comment]
Thank you for the information! We have been using VDJTools instead for the time being.
