### ISSUE TITLE
Error when running trust4-stats.py

### ISSUE THREAD

**Issue by oO828** [liulab-dfci/TRUST4#314]
Hello,

Thank you for developing TRUST4!
I am writing to seek your assistance with the trust4-stats.py script. I am attempting to process an output file named trust_report.tsv generated by TRUST4 using the trust4-stats.py script. However, I have encountered some errors that I am unable to resolve on my own.
When I run the following command:
Python trust-stats.py -r Con_1_report.tsv -f TRUST4_report --ntaa nt
Traceback (most recent call last):
File "trust-stats.py", line 102, in <module>
    chainType = GetChainType(cols[4], cols[6], cols[7])
File "trust-stats.py", line 23, in GetChainType
    return (0, isotypeRanks[c])
KeyError: 'IGHA'
To address this error, I added 'IGHA': 9 to the isotypeRanks dictionary and updated the isotypeOrder list accordingly. However, upon re-running the script, I encountered a new error:
Traceback (most recent call last):
File "trust-stats.py", line 106, in <module>
    if (cols[3] not in immrep[chainType]):
KeyError: (0, 10)
I suspect that the issue might be related to the nested structure of the subsequent code, but I am not certain how to modify it to resolve it correctly. Any guidance or suggestions you could provide would be greatly appreciated.

**Comment by mourisl** [comment]
Sorry for the delayed reply. I think you may also need to update line91 so the immrep array have the element pre-allocated. I'll modify the scripts later to make it easier to use/update.
